logging:
  level:
    .: error
    org.springframework: ERROR
    com.mkyong: ERROR

spring:
  profiles:
    active: "dev"
  resources:
    static-locations: classpath:/static/

springdoc:
  swagger-ui:
    path: /v3/swagger-ui
    
server:
  port: 8082
      
---

spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/identity
    username: root
    password: cofomo.123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      
swagger:
  basepath: http://localhost:8082
  description: Test server on localhost
  
basepath: http://localhost:8082
      
---

spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://mysql:3306/identity
    username: root	
    password: cofomo.123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update

swagger:
  basepath: https://authority.cofomo.io/api
  description: Test server for deployment

basepath: http://authority.cofomo.io


